M48
; DRILL file {KiCad (6.0.1)} date Fri Jan 28 19:13:07 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-28T19:13:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X99.06Y-58.42
X99.06Y-73.66
X114.3Y-58.42
X114.3Y-73.66
T0
M30
